export const SET_PERSONAL_INFO = "SET_PERSONAL_INFO";
export const SET_SKILLS_INFO = "SET_SKILLS_INFO";
export const SET_EDUCATION_INFO = "SET_EDUCATION_INFO";
export const SET_JOB_INFO = "SET_JOB_INFO";
export const SET_INTEREST_INFO = "SET_INTEREST_INFO";

export const NEXT_TO_SKILLS = "NEXT_TO_SKILLS";
