export const SET_PERSONAL_INFO = "SET_PERSONAL_INFO";
export const SET_SKILLS_INFO = "SET_SKILLS_INFO";
export const SET_EDUCATION_INFO = "SET_EDUCATION_INFO";
export const SET_JOBS_INFO = "SET_JOBS_INFO";
export const SET_INTEREST_INFO = "SET_INTEREST_INFO";

export const NEXT_TO_SKILLS = "NEXT_TO_SKILLS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_ERRORS = "GET_ERRORS";
