export const SET_PERSONAL_INFO = "SET_PERSONAL_INFO";
export const SET_SKILL_INFO = "SET_SKILL_INFO";
export const SET_EDUCATION_INFO = "SET_EDUCATION_INFO";
export const SET_JOB_INFO = "SET_JOB_INFO";
export const SET_INTEREST_INFO = "SET_INTEREST_INFO";
